### ISSUE TITLE
Bug: 404s for Exotic native cli in install script

### ISSUE THREAD

**Issue by reece-oliver** [sdkman/sdkman-cli-native#63]
Not sure if this is the right place, but this repo has most eyes on it.

Using the sdkman install script (https://get.sdkman.io/) - I am running this on s390x machine and it seems the Exotic version is missing as Im getting 404s this used to work fine.

https://api.sdkman.io/2/broker/download/native/install/0.0.15/Exotic

```
curl: (22) The requested URL returned error: 404

'curl --fail --location --progress-bar "$download_url" > "$sdkman_zip_file"': command failed with exit code 22.
```

**Comment by marc0der** [comment]
Hi @reece-oliver, could you please past a full log of the error you see when you run the installer? I wasn't aware that this was causing the install script to fail.

Also worth noting that we only support a small group of the most common platforms with the native client. If your platform does not fall in this group (ie is Exotic) then we don't support it. In this case, the API will always return the 404 you are seeing.

Also, if your platform is common and we missed it, and given there is a high demand for it, we could certainly support it.

But first, let's fix the issue if the installer is broken.

**Comment by reece-oliver** [comment]
So I had this running fine on a s390x machine for a while and had no problems and recently it has stopped working. I had a look at the script and saw s390x wasn't there so assumed it would come under exotic. This used to work fine, FYI I added prints for the download URLs so I knew what url it was trying to get the CLI from 

```
Installing script cli archive...
* Downloading...https://api.sdkman.io/2/broker/download/sdkman/install/5.16.0/exotic
######################################################################################################################################################################################################### 100.0%
* Checking archive integrity...
* Extracting archive...
* Copying archive contents...
* Cleaning up...

* Downloading...https://api.sdkman.io/2/broker/download/native/install/0.0.15/exotic
curl: (22) The requested URL returned error: 404

'curl --fail --location --progress-bar "$download_url" > "$sdkman_zip_file"': command failed with exit code 22.
```

**Comment by marc0der** [comment]
Okay, so the fix would be to bypass downloading of exotic native binaries when such a platform is detected. I'll see if I can roll something out soon to correct that.

**Comment by reece-oliver** [comment]
@marc0der Thank you, I would appreciate if you could get to it ASAP as it's currently blocking me get new build images out

**Comment by marc0der** [comment]
@reece-oliver To be honest, I'll probably only get around to this next week when I'm back from my holidays. I'll let you know when I've deployed that change.

**Comment by marc0der** [comment]
Okay, I couldn't resist. I fixed it :laughing: 

I've deployed a fix to the beta channel. If you can test that it works, I'll promote this to the stable channel @reece-oliver

**Comment by reece-oliver** [comment]
Yes that fixed the issue, thank you so much @marc0der. Deploy away

**Comment by marc0der** [comment]
Okay, that is now deployed to stable.

**Comment by reece-oliver** [comment]
Yes happy everything works
